# Generated by Django 4.0.4 on 2022-05-16 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDemandaOferta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombrecategoria', models.CharField(max_length=30, null=True, unique=True)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Categoria Demanda Oferta',
                'verbose_name_plural': 'Categoria Demanda Oferta',
            },
        ),
        migrations.CreateModel(
            name='DemandaPyme',
            fields=[
                ('id_dp', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_dp', models.CharField(max_length=100)),
                ('demandapyme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandaspyme', to='core.categoriademandaoferta', to_field='nombrecategoria')),
                ('idcategoriademaandaoferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoriademandaoferta')),
            ],
            options={
                'verbose_name': 'Demanda Pyme',
                'verbose_name_plural': 'Demanda Pyme',
            },
        ),
        migrations.CreateModel(
            name='IndustriaPyme',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreindustria', models.CharField(max_length=50)),
                ('descripcionindustria', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Industria Pyme',
                'verbose_name_plural': 'Industria Pyme',
            },
        ),
        migrations.CreateModel(
            name='OfertaPyme',
            fields=[
                ('id_op', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_op', models.CharField(max_length=100)),
                ('idcategoriademandaoferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoriademandaoferta')),
            ],
            options={
                'verbose_name': 'Oferta Pyme',
                'verbose_name_plural': 'Oferta Pyme',
            },
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombretipousuario', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tipo Usuario',
                'verbose_name_plural': 'Tipo Usuario',
            },
        ),
        migrations.CreateModel(
            name='MatchOfertaDemanda',
            fields=[
                ('ofertapyme_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='core.ofertapyme')),
                ('demandapyme_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.demandapyme')),
            ],
            options={
                'verbose_name': 'Match Oferta Demanda',
                'verbose_name_plural': 'Match Oferta Demanda',
            },
            bases=('core.demandapyme', 'core.ofertapyme'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
                ('idtipousuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipousuario')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuario',
            },
        ),
        migrations.CreateModel(
            name='Pyme',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombrepyme', models.CharField(max_length=50, null=True, unique=True)),
                ('rutpyme', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=100)),
                ('comuna', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField()),
                ('whatsapp', models.CharField(max_length=15)),
                ('telegram', models.CharField(max_length=20)),
                ('idindustriapyme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.industriapyme')),
                ('idusuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
            options={
                'verbose_name': 'Pyme',
                'verbose_name_plural': 'Pyme',
            },
        ),
        migrations.AddField(
            model_name='ofertapyme',
            name='idpymeo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nombrespymee', to='core.pyme', to_field='nombrepyme'),
        ),
        migrations.AddField(
            model_name='ofertapyme',
            name='ofertapyme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertaspyme', to='core.categoriademandaoferta', to_field='nombrecategoria'),
        ),
        migrations.AddField(
            model_name='demandapyme',
            name='idpymed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nombrespyme', to='core.pyme', to_field='nombrepyme'),
        ),
    ]
